### ISSUE TITLE
"Aquire Primitive JD" edit suggestions

### ISSUE THREAD

**Issue by Fzzr** [AlexBassett/ES-JD-Plugin#1]
https://github.com/AlexBassett/ES-JD-Plugin/blob/4e1e2dee8a401bf4bf87d7c18c0aadfa954e5060/data/missions.txt#L11

* Remove "surprisingly," the unexpected results speak for themseleves.
* Remove "only" since you're not noting the absence of something expected but rather the replacement of one thing with another.
* Builtin life support doesn't make sense to connect to maintaining an orbit. Maybe remove that sentence entirely since it doesn't add to the following sentence.
* Remove "What concerns you is how" and start that sentence at "There". There's no need to insert thoughts into the player's head in this case, since it's a description.
* Remove "an unfamiliar sight" since that's redundant with saying it's an odd JD.
* Remove trailing space at the end of the line.

https://github.com/AlexBassett/ES-JD-Plugin/blob/4e1e2dee8a401bf4bf87d7c18c0aadfa954e5060/data/missions.txt#L14

The sentences are a bit long. Break the first sentence up at "you" and the second sentence at "gravity". 

https://github.com/AlexBassett/ES-JD-Plugin/blob/4e1e2dee8a401bf4bf87d7c18c0aadfa954e5060/data/missions.txt#L32

Do not capitalize "human" or "alien", since they're not proper nouns.

https://github.com/AlexBassett/ES-JD-Plugin/blob/4e1e2dee8a401bf4bf87d7c18c0aadfa954e5060/data/missions.txt#L33

The bit about being unsure isn't necessary. Just add "The ship looks abandoned."  to the previous line.

**Comment by AlexBassett** [comment]
Thanks

**Comment by Fzzr** [comment]
Fixed in ada361b5bb50798605350d33b8a3e04cff2a1ac0
